version: '3'

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3336:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_HOST: ${DB_HOST:-mysql}
      MYSQL_DATABASE: ${DB_DATABASE:-mintos}
      MYSQL_USER: ${DB_USERNAME:-dbuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-dbpass}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-dbpass}
    networks:
      - mintos

  nginx:
    image: nginx:1.13-alpine
    ports:
      - 9000:80
      - 9001:81
      - 9002:82
    volumes:
      - .:/srv/www
      - ./docker/nginx/laravel.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/symfony.conf:/etc/nginx/conf.d/symfony.conf
      - ./docker/nginx/yii2.conf:/etc/nginx/conf.d/yii2.conf
    networks:
      - mintos

  php-fpm:
    build:
      context: docker
      dockerfile: php.Dockerfile
    ports:
      - 9000
    volumes:
      - .:/srv/www
    networks:
      - mintos

  init-cmd:
    build:
      context: docker
      dockerfile: php.Dockerfile
    environment:
      MYSQL_HOST: ${DB_HOST:-mysql}
      MYSQL_DATABASE: ${DB_DATABASE:-mintos}
      MYSQL_USER: ${DB_USERNAME:-dbuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-dbpass}
      MYSQL_ROOT_USER: ${DB_USERNAME:-root}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-dbpass}
      API_URL: ${API_URL:-http://127.0.0.1:9000/api}
      API_ENV: ${APP_ENV:-dev}
      FORCE_FRESH: ${FORCE_FRESH:-true}
    volumes:
      - .:/srv/www
    command: "sh /srv/www/docker/init.sh"
    networks:
      - mintos
    depends_on:
      - mysql
      - nginx
      - php-fpm

  yarn:
    image: node:12
    working_dir: /srv/www/frontend
    command: "yarn docker-dev"
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/srv/www/frontend
    environment:
      API_URL: ${API_URL:-http://127.0.0.1:9000/api}
    networks:
      - mintos

networks:
  mintos:

volumes:
  db_data:
